### ISSUE TITLE
Will not work on CentOS

### ISSUE THREAD

**Issue by cyberscribe** [rothgar/ansible-yum-security-updates#1]
Per this forum discussion: https://www.centos.org/forums/viewtopic.php?f=47&t=51300 - the security meta-data _may_ be present in EPEL, but not the main CentOS repositories, so installing this set of tools will not help you to install security-only updates on CentOS, only RedHat. Beware.

**Comment by rothgar** [comment]
Thanks for the clarification. It was only targeted for rhel 5 and rhel 6. I hope the readme and code is clear about that.

**Comment by cyberscribe** [comment]
Feel free to delete if you think unnecessary--I found this repo. on a
Google search for CentOS solutions to security-only updates via yum, hence
my placing this as a flag in case it's useful to others.

**Comment by rothgar** [comment]
Just pushed a note to the readme.
